### ISSUE TITLE
Display bug in Firefox

### ISSUE THREAD

**Issue by roSievers** [nomeata/incredible#77] opened 2015-12-20 11:29 UTC
The blocks are broken in my Firefox, but Chromium is fine (Ubuntu 14.04, Firefox 43.0). See attached screenshot. The problem persists when using a new Firefox profile with no add-ons installed. (Ubuntu Guest Profile)

![displaybuginfirefox](https://cloud.githubusercontent.com/assets/757602/11917741/b2d24e7a-a714-11e5-8533-2600feae5f0d.jpg)

**Comment by nomeata** [comment] 2015-12-20 21:02
I develop the incredible proof machine on Firefox exclusively, but I’m still on 38 (using Debian unstable here), and here everything works.

@all: Can someone else reproduce this problem?

**Comment by roSievers** [comment] 2015-12-20 21:10
It is working fine on my girlfriends Firefox (Mac OS, Firefox 42.0). I guess something on my end is causing that bug.

**Comment by nomeata** [comment] 2015-12-20 21:35
Ok, thanks for checking. Marking it as `invalid` for now, but if you know more (and it’s something we can fix), then please report back!

**Closed by nomeata** 2015-12-20 21:35 UTC
Labels: invalid, UI

**Comment by gattschardo** [comment] 2015-12-21 18:13
It works for me with Firefox 42.0 (on Arch Linux), so probably not a linux-specific issue either.
