### ISSUE TITLE
Stuck... P(C_4) =/= P(Y_5) ?

### ISSUE THREAD

**Issue by TimJSwan89** [nomeata/incredible#80] opened 2016-03-17 03:19 UTC
Hi, I am on the 9th puzzle of session 6. 
https://gyazo.com/010e9a0d88d693e2938c775bcaff0a36
I'm not sure, but isn't this supposed to work?
Even if I have it wrong, shouldn't the errors be symmetric across the 'OR' block?

**Comment by nomeata** [comment] 2016-03-17 09:29
>  I'm not sure, but isn't this supposed to work?

The problem is that the the constants like `c₄` can only be used within the scope of the ∃-elimination block; they are local. Try to make that block as large as you can, by pulling the `⋅∨` inside, and also the ∃-introduction block (of which you’ll need two).

>  Even if I have it wrong, shouldn't the errors be symmetric across the 'OR' block?

Depending on the processing order of connections, errors can show up in either place. We decided to be deterministic based on the order of creation (which is generally more predictable). It looks as if you wired both sides up differently.

I’ll close this bug to get it off the list of open issues, but feel free to continue discussing this here!

**Closed by nomeata** 2016-03-17 09:29 UTC

**Comment by TimJSwan89** [comment] 2016-03-17 14:44
Wow, thanks!
Hey, I really like the idea of making Haskell type languages easier to work with. I've had so much trouble with libraries that it's pushed me to formalize what is actually going on. I came to an interesting conclusion that merged with an app that I already was designing. It came out two years ago, 'Inspiration Basic.' Essentially, it is considered educational since you can just program using deterministic options and don't need to Google anything. However, I realized that this can be done with dependently typed or functionally typed languages and the usefulness potentially increases dramatically to industry level or education for post-graduates. Instead of complexity growing at ~2^(7^n) with n the height of the proof/software abstraction, it can remain at ~100, which should only become clear in large enough projects. Also, switching from a system that requires compilation of topological files is n when it can be log n for the amount of code. I came up with a system which formally separates an intuitionistic style pure functional section of the software on top then at the bottom, turing complete and state, hardware and I/O based code. The idea being that the bottom code is so short that it is easily formalized manually, but the top code is always formalized by construction. Are you familiar with AGDA? I think I can make it change from specialized to fundamentally useful.

**Comment by TimJSwan89** [comment] 2016-03-18 19:46
I'm stuck again.
https://gyazo.com/68292d21678812285f6239fa428d2525

**Comment by TimJSwan89** [comment] 2016-03-18 19:53
Does 'y' have a different meaning than 'c' as a parameter? Because in this instance:
https://gyazo.com/438dd0861a75f5d9e78e325fae3937e6
I can construct a 'for all' statement just given a 'c'. But in the puzzle that I am stuck on, I cannot infer more than y.

**Comment by nomeata** [comment] 2016-03-18 20:59
`y` is a free variable, and can be instantiated to any term. `c` is a constant, and cannot be further instantiated.

**Comment by TimJSwan89** [comment] 2016-03-18 23:00
I muse be misunderstanding.. if the proof ends with an 'There exists..' statement, then mustn't the block before that be an exists introduction? If so, then I would have to prove an example element not being true for P, which is not necessarily a true statement. How would this be possible then?

**Comment by nomeata** [comment] 2016-03-20 21:15
> if the proof ends with an 'There exists..' statement, then mustn't the block before that be an exists introduction?

Not necessarily. There are plenty of blocks that produce an arbitrary `P` that can be instantiated to an `∃x....` formula.

I believe that for that task, you will have to use `TND` in a clever way.

**Comment by TimJSwan89** [comment] 2016-03-30 18:17
Right. This was where I had gotten.
https://gyazo.com/6e41204ca85b01e24fba73d26fc29b4e

**Comment by nomeata** [comment] 2016-03-31 07:12
Hmm, at this point, I don’t think I have any insightful advice to offer (besides just showing you a complete solution).

**Comment by TimJSwan89** [comment] 2016-04-04 22:52
I suppose having blocks is useful intuitively, but unless it is absolutely clear which blocks can validly be combined with others, there is still some non-determinism involved. In case it is pretty deterministic, is the solution quite large or complex? I did see an image online before which had many many pieces and used LEM twice.
